### ISSUE TITLE
Request for simple compute shader example

### ISSUE THREAD

**Issue by SuperSimon81** [fbertola/bgfx-python#15]
I am currently trying to implement compute shaders in my project. It is difficult to find information on how to go about it. So far I have tried dissecting some of natrix code and looking at the bgfx examples that use compute shaders. No success. 

Would it be possible for you to make a minimal compute shader example in bgfx-python?

**Comment by fbertola** [comment]
Hi @SuperSimon81. Sure, I could add a minimal example, but It would be helpful to know what difficulties you have. Natrix should be a great starting point, as the demo code contains a minimal example for compute shaders.

**Comment by SuperSimon81** [comment]
I will look at Natrix again and formulate more specific questions.

**Comment by SuperSimon81** [comment]
I´ve made an extremely simple compute shader that writes to a texture that is then drawn on a quad.

What I am struggling with is understanding how to pass data to the compute shaders, and then read back the output. Im assuming I need something like a SSBO. Ive seen how you use set_buffer in Natrix, but I cant figure out how you are reading the output from the compute shaders back.  

Lets say I have a 200 vec2s and i want to calculate the distance between all consecutive two vec2s, ie the distance between 1 and 2, 3 and 4 etc.. How would I pass the 200 vec2s to 100 compute shaders and read back the 100 element float list? 

Any advice would be greatly appreciated

**Comment by fbertola** [comment]
As far as I know SSBO is not yet supported on BGFX. My approach would be to create a read-back texture as the output of the compute shaders. See for example here: https://github.com/bkaradzic/bgfx/blob/master/examples/30-picking/picking.cpp.

If you need more advanced support on BGFX, I think you will have more luck opening an issue on the original repo or through its Gitter.

**Comment by fbertola** [comment]
I'll close this issue since on further input was given.
