### ISSUE TITLE
setup.py install fails with ninja error

### ISSUE THREAD

**Issue by WanderingMacUser** [fbertola/bgfx-python#3]
I followed the instructions, and made sure that I have all the required libraries,  but setup.py fails due to an error from ninja complaining about missing libbxRelease.a. I am don't have much experience with compiling C++ or using ninja and don't know how to fix this, am I missing a library or something? 
Here is the output from setup.py: [Console Output.txt](https://github.com/fbertola/bgfx-python/files/4295834/Console.Output.txt)

I am running macOS 10.14.6 and python 3.8.1, cmake, make, and ninja are all the most up to date versions on homebrew as of 3/4/2020.

**Comment by fbertola** [comment]
From your console output:
```
In file included from ../../../../bx/src/allocator.cpp:6:
In file included from ../../../../bx/src/bx_p.h:42:
../../../../bx/include/bx/bx.h:9:10: fatal error: 'alloca.h' file not found
#include <alloca.h> // alloca
         ^~~~~~~~~~
```
This happens if you don't have installed the MaxOS SDK and/or if you recently updated to Catalina.
Here is a checklist to ensure that your system is up to date:
* make sure to have the latest version from `master`
* check if you have the Command Line Tools installed: `xcode-select --install`
* check that this path exists: `ls -la /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

**Comment by darkimage** [comment]
hello sorry to plug here but i'm having the same issue but on windows cmake fails this is the [console log](https://github.com/fbertola/bgfx-python/files/4318743/Console_Log.txt)
 (i'm using Visua Studio 2019 with VSBuildTool 141 (2017) i changed it using [this method](https://developercommunity.visualstudio.com/comments/537831/view.html) ) and this is the 
[CMakeError.log](https://github.com/fbertola/bgfx-python/files/4318748/CMakeError.log) of cmake,
i dont know if its faulty setup or else but it seem that a bx flag during compiling is not set.

**Comment by darkimage** [comment]
i've installed and retried with Visual Studio 2017 but it still give me the same errors

**Comment by fbertola** [comment]
@darkimage Yes there is an issue with windows build right now. I'm currently working on resolving it, thanks for the input!

**Comment by darkimage** [comment]
@fbertola dont worry i thought it was only on my side, if you need more logs or debug infos let me know

**Comment by fbertola** [comment]
@darkimage Windows build should now work as expected.

**Comment by darkimage** [comment]
@fbertola yup it's now working great, thank you!
one thing to mention it's that i had uninstall vs 2017 because the setup.py was still trying to use the v141 compiler tools and that lead to errors during the compilation.
the setup.py still search for 2017 v141 but hookup the v142 just fine (maybe this can cause confusion)

**Comment by fbertola** [comment]
Good point, I'll have a look. Thanks!

**Comment by WanderingMacUser** [comment]
I apologize for not getting back to this sooner, I got swept up in the chaos of the last two weeks and completely forgot about this. 
It turns out that something was wrong with my installation of the command line tools, I uninstalled them with `sudo rm -rf /Library/Developer/CommandLineTools` and re-installed them and was able to compile the latest master successfully. However the bindings scripts fail with:

`Traceback (most recent call last):
  File "make_bindings_bgfx.py", line 9, in <module>
    binder_executable = glob.glob(
IndexError: list index out of range`

I think something might be wrong with the path on line 8 but I don't know what it should be pointing too.

**Comment by fbertola** [comment]
@WanderingMacUser you should install `binder` in that directory: https://github.com/RosettaCommons/binder.
Basically, clone the repository then execute this script: `binder/build-and-run-tests.py`. The generated .cpp files needs some touch up, so it's not entirely an automated process, but it helps a lot.

**Comment by fbertola** [comment]
I'm closing this issue for lack of additional inputs.
