### ISSUE TITLE
Request for texture mapping example

### ISSUE THREAD

**Issue by SuperSimon81** [fbertola/bgfx-python#9]
If you would consider adding an example of texture mapping it would really help me out. Something simple like slapping a small texture on the cubes example. 

The c++ bgfx texture mapping example uses some bgfx_util loadTexture function that I cant find in bgfx-python. Im not sure how to load the image into the texture using bgfx.copy and keep failing.

**Comment by fbertola** [comment]
I could surely help. Actually I was working on wrapping the other utilities for texture and meshes. If you have a little patience I'll add the examples in a week or two.
